# Generated by Django 4.1.3 on 2022-12-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
