# Generated by Django 4.1.3 on 2022-12-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_subscribe_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='user_name',
        ),
    ]
