# Generated by Django 4.1.3 on 2023-01-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_alter_subscribe_option'),
    ]

    operations = [
    ]
