# Generated by Django 4.1.3 on 2023-01-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_jobpost_type'),
    ]

    operations = [
    ]
