# Generated by Django 4.1.3 on 2023-02-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20230120_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
